In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
Aaa_datframe = pd.read_csv("./Aaa.csv")

In [4]:
Aaa_datframe.head(15)

0         1         2         3         4         5         6  \
0   5.166734  0.026853  0.763455 -1.616877 -0.799775 -1.069787  0.855939   
1   5.506258  0.611098  0.925470 -1.971487 -1.073066 -1.167567  0.862813   
2   5.826925  0.227678  0.546047 -1.347163 -0.963003 -1.667765  0.778091   
3   5.662545  0.411558  0.750861 -1.796695 -0.760791 -1.774797  0.594941   
4   4.898424  0.498687  0.846236 -2.038857 -0.898690 -1.731955  0.589366   
5   6.212292  1.033064  0.448523 -1.064100 -1.565042 -1.993595  1.464151   
6   6.070476  1.299193  0.567709 -0.654809 -1.397000 -2.307791  1.726774   
7   5.592068  1.657183  0.549357 -0.698111 -1.333423 -2.436237  1.436796   
8   5.951328  1.512480  0.484877 -1.213961 -1.354297 -2.166807  1.542230   
9   5.200798  1.448562  0.847422 -1.087964 -1.373839 -2.099625  1.771703   
10  6.107957  4.282798  1.728319  0.079448  0.675644 -0.577020  0.459542   
11  6.349375  4.011372  1.613123 -0.359192  0.287736 -0.804447  0.393512   
12  6.076453  4.174243  1.604929 -0.180644  0.568566 -0.612940  0.537206   
13  5.755143  3.920653  1.777239  0.051074  0.473238 -0.522985  0.534534   
14  6.237066  4.088832  1.391420 -0.348107  0.562881 -0.669416  0.528540   

           7         8         9  ...       208       209       210       211  \
0   1.694199 -1.518422 -1.217447  ...  0.018342  0.019636  0.016025  0.017005   
1   1.628060 -1.536581 -1.318965  ...  0.019245  0.016519  0.018038  0.014005   
2   1.413097 -1.886133 -1.647901  ...  0.019057  0.017567  0.014608  0.015075   
3   1.563014 -1.493957 -1.813214  ...  0.021548  0.019103  0.016814  0.014630   
4   1.695544 -1.508400 -1.978644  ...  0.024647  0.016922  0.016799  0.013548   
5  -0.086121 -0.682505 -0.892820  ...  0.017581  0.017732  0.019671  0.016967   
6  -0.253720 -0.647977 -0.486380  ...  0.020302  0.023449  0.023616  0.016253   
7  -0.320476 -0.636331 -0.473055  ...  0.021378  0.020914  0.024524  0.021873   
8  -0.597047 -0.676161 -0.449066  ...  0.024380  0.025333  0.023995  0.016333   
9  -0.289421 -0.852601 -0.581026  ...  0.024359  0.023613  0.024640  0.017351   
10 -0.482528  0.289613 -0.121268  ...  0.022776  0.021928  0.020742  0.019126   
11 -0.379780  0.775061 -0.516886  ...  0.020606  0.021203  0.018413  0.017482   
12 -0.122820  0.677724 -0.335619  ...  0.024336  0.023266  0.018410  0.016496   
13 -0.088256  0.491485 -0.340173  ...  0.019928  0.021022  0.019168  0.017264   
14 -0.058522  0.570531 -0.327737  ...  0.024798  0.022679  0.016956  0.015655   

         212       213       214       215  216  \
0   0.016756  0.013297  0.014664  0.012849  1.0   
1   0.014021  0.014458  0.015211  0.012715  1.0   
2   0.016047  0.014264  0.014848  0.012004  1.0   
3   0.014834  0.016101  0.017660  0.014554  1.0   
4   0.014354  0.019226  0.019045  0.015774  1.0   
5   0.015321  0.014267  0.016003  0.015786  0.0   
6   0.017608  0.015063  0.017968  0.013886  0.0   
7   0.016790  0.017216  0.016395  0.015358  0.0   
8   0.016463  0.017115  0.016458  0.015722  0.0   
9   0.015175  0.016321  0.018350  0.016102  0.0   
10  0.018507  0.014674  0.013428  0.014836  0.0   
11  0.021821  0.018241  0.014415  0.016225  0.0   
12  0.022190  0.019168  0.015458  0.014404  0.0   
13  0.018535  0.017486  0.013377  0.013866  0.0   
14  0.019462  0.016462  0.014811  0.014722  0.0   

                                                  217  
0   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
1   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
2   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
3   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
4   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
5   2017_01_12_10_45_Priyanka_C_Na_F_Na_28_160_59_...  
6   2017_01_12_10_45_Priyanka_C_Na_F_Na_28_160_59_...  
7   2017_01_12_10_45_Priyanka_C_Na_F_Na_28_160_59_...  
8   2017_01_12_10_45_Priyanka_C_Na_F_Na_28_160_59_...  
9   2017_01_12_10_45_Priyanka_C_Na_F_Na_28_160_59_...  
10  2016_07_21_03_10_Madhivanan_C_Na_M_Na_28_171_7...  
11  2016

In [5]:
Aaa_datframe.shape

(453, 218)

In [6]:
Aaa_datframe["216"].value_counts()

0.0    248
1.0    205
Name: 216, dtype: int64

In [7]:
Aaa_datframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Columns: 218 entries, 0 to 217
dtypes: float64(217), object(1)
memory usage: 771.6+ KB


In [8]:
Aaa_datframe.isnull().sum()

0      0
1      0
2      0
3      0
4      0
      ..
213    0
214    0
215    0
216    0
217    0
Length: 218, dtype: int64

In [9]:
X = Aaa_datframe.iloc[:,:216]

In [10]:
y = Aaa_datframe.iloc[:,216]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [13]:
X_train.shape

(362, 216)

In [14]:
X_test.shape

(91, 216)

In [15]:
y_train.shape

(362,)

In [16]:
y_test.shape

(91,)

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)


In [21]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [22]:
svc = SVC()

svc.fit(X_train,y_train)
y_pred_default = svc.predict(X_test)


print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred_default)))

y_pred_train = svc.predict(X_train)
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Model accuracy score with default hyperparameters: 0.6923
Training-set accuracy score: 0.9420


### Hyperparameter Tuning

In [23]:
svc_1 = SVC(C = 100.0)
svc_1.fit(X_train,y_train)

y_pred = svc_1.predict(X_test)

print('Model accuracy score with rbf kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with rbf kernel and C=100.0 : 0.7582


In [24]:
y_pred_train = svc_1.predict(X_train)

print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

In [26]:
scv_2 = SVC(C = 1000.0)
scv_2.fit(X_train,y_train)

y_pred = scv_2.predict(X_test)

print('Model accuracy score with rbf kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with rbf kernel and C=1000.0 : 0.7582


### Kernel Trick

In [27]:
linear_svc=SVC(kernel='linear', C=1.0) 
linear_svc.fit(X_train,y_train)
y_pred_linear = linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_linear)))

Model accuracy score with linear kernel and C=1.0 : 0.6154


In [30]:
linear_svc=SVC(kernel='linear', C=100.0) 
linear_svc.fit(X_train,y_train)
y_pred_linear = linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_linear)))

y_pred_train = linear_svc.predict(X_train)

print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

# print("hi")

Model accuracy score with linear kernel and C=1.0 : 0.7253
Training-set accuracy score: 1.0000


In [31]:
poly_svc = SVC(kernel = 'poly')
poly_svc.fit(X_train,y_train)

y_pred_poly = poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_poly)))



Model accuracy score with polynomial kernel and C=1.0 : 0.6264


In [33]:
poly_svc = SVC(kernel = 'poly', C=1000)
poly_svc.fit(X_train,y_train)

y_pred_poly = poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_poly)))

y_pred_train = poly_svc.predict(X_train)

print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))


Model accuracy score with polynomial kernel and C=1000.0 : 0.8242
Training-set accuracy score: 1.0000


In [34]:
sigmoid_svc = SVC(kernel = 'sigmoid', C = 1.0)
sigmoid_svc.fit(X_train,y_train)

y_pred_sigmoid = sigmoid_svc.predict(X_test)

print('Model accuracy score with sigmoid kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_sigmoid)))

Model accuracy score with sigmoid kernel and C=1.0 : 0.5275


In [35]:
sigmoid_svc = SVC(kernel = 'sigmoid', C = 100.0)
sigmoid_svc.fit(X_train,y_train)

y_pred_sigmoid = sigmoid_svc.predict(X_test)

print('Model accuracy score with sigmoid kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_sigmoid)))

Model accuracy score with sigmoid kernel and C=100.0 : 0.4286


### Inference

Empty

Continuing with Default Parameters, calculating confusion matrix, F1 scores.

In [36]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred_default)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])


from sklearn.metrics import classification_report
# print(classification_report(y_test,y_pred_default))

Confusion matrix

 [[39  7]
 [21 24]]

True Positives(TP) =  39

True Negatives(TN) =  24

False Positives(FP) =  7

False Negatives(FN) =  21


In [37]:
TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

### Kfold 

In [38]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [39]:
kfold = KFold(n_splits=5, shuffle=True)
kfold_svc = SVC()
default_kfold_scores = cross_val_score(kfold_svc,X,y, cv = kfold)

In [40]:
print('Stratified cross-validation scores with RBF kernel:\n\n{}'.format(default_kfold_scores))

Stratified cross-validation scores with RBF kernel:

[0.64835165 0.68131868 0.73626374 0.57777778 0.65555556]


In [42]:
default_kfold_scores.mean()

0.6598534798534799

In [43]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

svc = SVC()

param_grid = {'C': [0.1, 1, 10, 100, 1000],  
              'gamma':[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9], 
              'kernel': ['rbf']}  

grid_search = GridSearchCV(estimator=svc, param_grid=param_grid, scoring='accuracy', cv = kfold, verbose = 0)

In [44]:
grid_search.fit(X,y)

/home/akansh/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=True),
       error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [45]:
grid_search.best_score_

0.9337748344370861

In [46]:
grid_search.best_params_

{'C': 10, 'gamma': 0.2, 'kernel': 'rbf'}

In [47]:
grid_search.best_estimator_

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.2, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### Hyperparameter C = 10 and gamma = 0.1, kernel = 'rbf'

In [53]:
kfold = KFold(n_splits=5, shuffle=True)
kfold_svc = SVC(C = 10,gamma=0.2 )
kfold_scores = cross_val_score(kfold_svc,X,y, cv = kfold)


In [54]:
kfold_scores

array([0.96703297, 0.91208791, 0.93406593, 0.86666667, 0.93333333])

In [55]:
kfold_scores.mean()

0.9226373626373625

In [56]:
svc = SVC(C = 10, gamma=0.2)

svc.fit(X_train,y_train)
y_pred_default = svc.predict(X_test)


print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred_default)))

y_pred_train = svc.predict(X_train)
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Model accuracy score with default hyperparameters: 0.5055
Training-set accuracy score: 1.0000
