In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate

In [3]:
from sklearn.model_selection import learning_curve 

In [4]:
import matplotlib.pyplot as plt 

In [5]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
Cough_dataframe = pd.read_csv("./cough.csv")

In [7]:
Cough_dataframe.head()

0         1         2         3         4         5         6  \
0 -1.049566 -0.724346 -0.643932 -1.312013  0.753689 -0.749393  0.948658   
1 -0.061991 -0.409625 -0.595233 -1.286315  0.849574 -0.234460  1.107897   
2  0.507403  0.534974  0.407169 -0.947500  0.590494 -0.218818  0.849918   
3  0.433352 -0.859231  0.815786  0.382931  1.386598  0.363840  1.678211   
4  0.332375 -2.898388  1.046713  1.091744  1.408277  0.348940  1.828713   

          7         8         9  ...       208       209       210       211  \
0 -0.194646 -0.415013  0.143907  ...  0.039689  0.037159  0.076035  0.050627   
1 -0.733951 -1.157121  0.326685  ...  0.039152  0.033323  0.032537  0.025178   
2 -0.478996 -1.118813  0.029738  ...  0.025266  0.039965  0.074801  0.062176   
3 -1.375525 -0.978809  0.045781  ...  0.024413  0.057612  0.041814  0.045293   
4 -1.360403 -1.343445  0.280000  ...  0.035699  0.032245  0.048694  0.034298   

        212       213       214       215  216  \
0  0.044381  0.032918  0.029141  0.050840  1.0   
1  0.038339  0.028534  0.034394  0.043211  1.0   
2  0.040444  0.031103  0.029153  0.052451  1.0   
3  0.032174  0.034572  0.032443  0.051107  1.0   
4  0.057311  0.057942  0.037740  0.083570  1.0   

                                                 217  
0  2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
1  2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
2  2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
3  2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
4  2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  

[5 rows x 218 columns]

In [8]:
Cough_dataframe.shape

(845, 218)

In [9]:
Cough_dataframe["216"].value_counts()

0.0    451
1.0    394
Name: 216, dtype: int64

In [10]:
X = Cough_dataframe.iloc[:,:216]

y = Cough_dataframe.iloc[:,216]

In [11]:
Cough_dataframe["216"]

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
840    1.0
841    1.0
842    1.0
843    1.0
844    1.0
Name: 216, Length: 845, dtype: float64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [13]:
X_train.shape

(676, 216)

In [14]:
X_test.shape

(169, 216)

In [15]:
y_train.shape

(676,)

In [16]:
y_test.shape

(169,)

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)


In [18]:
svc = SVC()

svc.fit(X_train,y_train)
y_pred_default = svc.predict(X_test)


print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred_default)))

y_pred_train = svc.predict(X_train)
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Model accuracy score with default hyperparameters: 0.8402
Training-set accuracy score: 0.9837


### Hyperparameter Tuning

In [48]:
svc_1 = SVC(C = 100.0)
svc_1.fit(X_train,y_train)

y_pred = svc_1.predict(X_test)

print('Model accuracy score with rbf kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with rbf kernel and C=100.0 : 0.9231


In [49]:
y_pred_train = svc_1.predict(X_train)

In [50]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 0.9852


In [51]:
scv_2 = SVC(C = 1000.0)
scv_2.fit(X_train,y_train)

y_pred = scv_2.predict(X_test)

print('Model accuracy score with rbf kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with rbf kernel and C=1000.0 : 0.9053


### Kernel Trick

In [52]:
linear_svc=SVC(kernel='linear', C=1.0) 
linear_svc.fit(X_train,y_train)
y_pred_linear = linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_linear)))

Model accuracy score with linear kernel and C=1.0 : 0.7929


In [68]:
linear_svc=SVC(kernel='linear', C=100.0) 
linear_svc.fit(X_train,y_train)
y_pred_linear = linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_linear)))



# print("hi")

In [54]:
poly_svc = SVC(kernel = 'poly')
poly_svc.fit(X_train,y_train)

y_pred_poly = poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_poly)))



Model accuracy score with polynomial kernel and C=1.0 : 0.6568


In [55]:
poly_svc = SVC(kernel = 'poly', C=1000)
poly_svc.fit(X_train,y_train)

y_pred_poly = poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_poly)))



Model accuracy score with polynomial kernel and C=1000.0 : 0.8935


In [56]:
sigmoid_svc = SVC(kernel = 'sigmoid', C = 1.0)
sigmoid_svc.fit(X_train,y_train)

y_pred_sigmoid = sigmoid_svc.predict(X_test)

print('Model accuracy score with sigmoid kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_sigmoid)))

Model accuracy score with sigmoid kernel and C=1.0 : 0.7515


In [57]:
sigmoid_svc = SVC(kernel = 'sigmoid', C = 100.0)
sigmoid_svc.fit(X_train,y_train)

y_pred_sigmoid = sigmoid_svc.predict(X_test)

print('Model accuracy score with sigmoid kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_sigmoid)))

Model accuracy score with sigmoid kernel and C=100.0 : 0.6095


### Inference

Highest Test set accuracy is obtained using RBF Kernal Trick. 
The value of C and Gamma stills needs optimization. At C = 100, Test set accuracy is high but Training Set accuracy is 1, which means Overfitting. 

Continuing with Default Parameters, calculating confusion matrix, F1 scores.

In [58]:

cm = confusion_matrix(y_test,y_pred_default)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])


# print(classification_report(y_test,y_pred_default))

In [70]:
TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

### Kfold 

In [21]:
kfold = KFold(n_splits=5, shuffle=True)
kfold_svc = SVC()
default_kfold_scores = cross_val_score(kfold_svc,X,y, cv = kfold)

In [22]:
print('Stratified cross-validation scores with RBF kernel:\n\n{}'.format(default_kfold_scores))

Stratified cross-validation scores with RBF kernel:

[0.66863905 0.76331361 0.72189349 0.75147929 0.75739645]


In [188]:

svc = SVC()

param_grid = {'C': [0.1, 1, 10, 100, 1000],  
              'gamma':[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9], 
              'kernel': ['rbf']}  

scores = ['precision', 'recall']
grid_search = GridSearchCV(estimator=svc, param_grid=param_grid, scoring='f1', cv = kfold, verbose = 1)

In [189]:
grid_search.fit(X,y)

Fitting 5 folds for each of 45 candidates, totalling 225 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 225 out of 225 | elapsed:  1.5min finished


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=True),
       error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='f1', verbose=1)

In [92]:
grid_search.

make_scorer(accuracy_score)

In [190]:
grid_search.best_score_

0.9462700076969175

In [191]:
grid_search.best_params_

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}

In [185]:
grid_search.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### Hyperparameter C = 10 and gamma = 0.1, kernel = 'rbf'

In [28]:
kfold = KFold(n_splits=5, shuffle=True)
kfold_svc = SVC(C = 10,gamma=0.1 )
kfold_scores = cross_val_score(kfold_svc,X,y, cv = kfold)


In [29]:
kfold_scores

array([0.96449704, 0.89349112, 0.94674556, 0.92307692, 0.95857988])

In [30]:
kfold_scores.mean()

0.9372781065088758

In [69]:
svc = SVC()


In [71]:
svc.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [72]:
y_pred_train = svc.predict(X_train)

In [73]:
y_train.shape

(676,)

In [74]:
y_pred_train.shape

(676,)

In [75]:
accuracy_score(y_train,y_pred_train)

0.764792899408284

In [76]:
cn = confusion_matrix(y_train,y_pred_train)

In [77]:
cn

array([[312,  51],
       [108, 205]])

In [2]:
from svm import *

ModuleNotFoundError: No module named 'svm'

In [126]:
prob = svm_problem(Y_lib,feature_vector)

In [186]:
param = svm_parameter('-v 10 -t 2 -c 1 -g 0.5')

In [187]:
m = svm_train(prob, param)

Cross Validation Accuracy = 65.2071%


### Train, Test, Valid

In [157]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [158]:
X_test, X_val, y_test, y_val = train_test_split(X_test,y_test, test_size = 0.35)

In [193]:
svm = SVC(C = 10, gamma=0.1)

In [194]:
svm.fit(X_train,y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [195]:
y_pred_train = svm.predict(X_train)
accuracy_score(y_train,y_pred_train)

1.0

In [196]:
y_pred_test = svm.predict(X_test)
accuracy_score(y_test,y_pred_test)

0.944954128440367

In [197]:
y_pred_val = svm.predict(X_val)
accuracy_score(y_val,y_pred_val)

0.95

### Kfold with C = 100

In [202]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.10)

In [335]:
clf = SVC(C = 100)
score = cross_val_score(clf, X_train,y_train, cv = 5)

In [336]:
score

array([0.90789474, 0.91447368, 0.90789474, 0.86184211, 0.80263158])

In [338]:
score = cross_validate(clf,X_train,y_train,return_estimator=True,cv = 5)

In [339]:
score.keys()

dict_keys(['fit_time', 'score_time', 'estimator', 'test_score', 'train_score'])

In [340]:
score['fit_time']

array([0.14998174, 0.11319232, 0.10339117, 0.10789609, 0.09945965])

In [341]:
score['test_score'].mean()

0.8789473684210527

In [342]:
score['train_score'].mean()

0.9848684210526315

In [343]:
test_error = []
for i in range(0,len(score['estimator'])):
    a = score['estimator'][i]
    a_pred = a.predict(X_test)
    test_error.append(accuracy_score(y_test,a_pred))
    print(classification_report(y_test,a_pred))

              precision    recall  f1-score   support

         0.0       0.94      0.90      0.92        51
         1.0       0.86      0.91      0.89        34

   micro avg       0.91      0.91      0.91        85
   macro avg       0.90      0.91      0.90        85
weighted avg       0.91      0.91      0.91        85

              precision    recall  f1-score   support

         0.0       0.94      0.90      0.92        51
         1.0       0.86      0.91      0.89        34

   micro avg       0.91      0.91      0.91        85
   macro avg       0.90      0.91      0.90        85
weighted avg       0.91      0.91      0.91        85

              precision    recall  f1-score   support

         0.0       0.90      0.90      0.90        51
         1.0       0.85      0.85      0.85        34

   micro avg       0.88      0.88      0.88        85
   macro avg       0.88      0.88      0.88        85
weighted avg       0.88      0.88      0.88        85

              preci

In [346]:
np.array(test_error).mean()

0.8870588235294118

### Kfold with C = 10, gamma = 0.1 and  Learning Curve

In [12]:
from sklearn.model_selection import learning_curve 


In [57]:
clf = SVC(C = 10, gamma=0.1)

In [84]:
sizes, training_scores, testing_scores = learning_curve(clf, X, y, cv=5, scoring='accuracy',train_sizes=np.linspace(0.01, 1.0, 50), shuffle=True) 

In [ ]:
sizes

In [74]:
(X.shape[0]/5)*4

676.0

In [ ]:
testing_scores[49].mean()

In [ ]:
mean_training = np.mean(training_scores, axis=1) 
Standard_Deviation_training = np.std(training_scores, axis=1) 
  
# Mean and Standard Deviation of testing scores 
mean_testing = np.mean(testing_scores, axis=1) 
Standard_Deviation_testing = np.std(testing_scores, axis=1) 
  
# dotted blue line is for training scores and green line is for cross-validation score 
plt.plot(sizes, mean_training, '--', color="b",  label="Training score") 
plt.plot(sizes, mean_testing, color="g", label="Cross-validation score") 