In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [80]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
Cough_dataframe = pd.read_csv("./cough.csv")

In [11]:
Cough_dataframe.head(15)

0         1         2         3         4         5         6  \
0  -1.049566 -0.724346 -0.643932 -1.312013  0.753689 -0.749393  0.948658   
1  -0.061991 -0.409625 -0.595233 -1.286315  0.849574 -0.234460  1.107897   
2   0.507403  0.534974  0.407169 -0.947500  0.590494 -0.218818  0.849918   
3   0.433352 -0.859231  0.815786  0.382931  1.386598  0.363840  1.678211   
4   0.332375 -2.898388  1.046713  1.091744  1.408277  0.348940  1.828713   
5   0.756454 -1.150198  0.159321  0.143539 -0.106622 -0.498361  1.066417   
6   0.630880 -0.380515  0.103592 -0.387018  0.080167 -0.347639  0.815974   
7   1.178357 -0.418724 -0.406056 -0.710216  0.250765 -0.661735  0.523842   
8   2.267273 -0.976034 -0.205491 -1.377150 -0.769840 -0.672648  0.151072   
9   1.662660 -1.953393  0.476195 -0.934384 -0.408059 -0.612277  0.017260   
10  1.765333 -1.210547  0.442376 -1.363221 -0.416798 -0.718590 -0.173374   
11  1.795099 -2.354785  0.461231 -1.185174 -1.010940 -0.729191  0.145930   
12  1.064139 -1.685754  0.840121 -0.908058 -0.597772 -0.396371 -0.276265   
13  3.101988  0.194972 -0.005084 -0.726109 -0.506389 -0.424827  0.872203   
14  3.516307  0.916563  0.557170 -0.404135 -0.342692 -0.629478  0.646456   

           7         8         9  ...       208       209       210       211  \
0  -0.194646 -0.415013  0.143907  ...  0.039689  0.037159  0.076035  0.050627   
1  -0.733951 -1.157121  0.326685  ...  0.039152  0.033323  0.032537  0.025178   
2  -0.478996 -1.118813  0.029738  ...  0.025266  0.039965  0.074801  0.062176   
3  -1.375525 -0.978809  0.045781  ...  0.024413  0.057612  0.041814  0.045293   
4  -1.360403 -1.343445  0.280000  ...  0.035699  0.032245  0.048694  0.034298   
5  -1.017123 -0.916758  0.572472  ...  0.029908  0.027698  0.028698  0.019246   
6  -0.714423 -0.853351  0.034184  ...  0.051573  0.045859  0.047665  0.032352   
7  -0.731414 -0.601734  0.423563  ...  0.062479  0.062674  0.058782  0.040672   
8  -0.353609 -0.775014  0.213452  ...  0.080881  0.034683  0.040456  0.050570   
9  -1.866771 -0.350770  0.667572  ...  0.061617  0.047349  0.029550  0.039250   
10 -1.500812 -0.915979  0.456149  ...  0.030648  0.034324  0.035296  0.040517   
11 -1.562351 -0.707345  0.596039  ...  0.030163  0.048743  0.029747  0.041739   
12 -1.679259 -0.316822  0.589805  ...  0.037055  0.056312  0.044236  0.042922   
13  0.282098 -0.183308  0.018384  ...  0.053015  0.057016  0.048115  0.036066   
14  0.014235 -0.198586 -0.055545  ...  0.047332  0.057685  0.043897  0.036160   

         212       213       214       215  216  \
0   0.044381  0.032918  0.029141  0.050840  1.0   
1   0.038339  0.028534  0.034394  0.043211  1.0   
2   0.040444  0.031103  0.029153  0.052451  1.0   
3   0.032174  0.034572  0.032443  0.051107  1.0   
4   0.057311  0.057942  0.037740  0.083570  1.0   
5   0.029311  0.025405  0.021784  0.042919  1.0   
6   0.026968  0.036241  0.033235  0.040653  1.0   
7   0.048272  0.059934  0.043825  0.040574  1.0   
8   0.071627  0.046759  0.035248  0.045973  1.0   
9   0.041511  0.042445  0.050268  0.033038  1.0   
10  0.031407  0.043830  0.033314  0.038739  1.0   
11  0.052732  0.048941  0.044054  0.044356  1.0   
12  0.045185  0.029333  0.040257  0.033702  1.0   
13  0.039250  0.029360  0.030961  0.034379  0.0   
14  0.028940  0.027984  0.030673  0.034023  0.0   

                                                  217  
0   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
1   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
2   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
3   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
4   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
5   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
6   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
7   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
8   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
9   2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
10  2018_08_21_12_40_EllammaK_P_Asthma_F_before_48...  
11  2018

In [7]:
Cough_dataframe.shape

(845, 218)

In [9]:
Cough_dataframe["216"].value_counts()

0.0    451
1.0    394
Name: 216, dtype: int64

In [12]:
Cough_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 845 entries, 0 to 844
Columns: 218 entries, 0 to 217
dtypes: float64(217), object(1)
memory usage: 1.4+ MB


In [13]:
Cough_dataframe.isnull().sum()

0      0
1      0
2      0
3      0
4      0
      ..
213    0
214    0
215    0
216    0
217    0
Length: 218, dtype: int64

In [15]:
X = Cough_dataframe.iloc[:,:216]

In [17]:
y = Cough_dataframe.iloc[:,216]

In [14]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [21]:
X_train.shape

(676, 216)

In [22]:
X_test.shape

(169, 216)

In [23]:
y_train.shape

(676,)

In [24]:
y_test.shape

(169,)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

In [27]:
X_train = scaler.fit_transform(X_train)

In [28]:
X_test = scaler.transform(X_test)

In [30]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)


In [32]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [65]:
svc = SVC()

svc.fit(X_train,y_train)
y_pred_default = svc.predict(X_test)


print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred_default)))

y_pred_train = svc.predict(X_train)
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Model accuracy score with default hyperparameters: 0.8698
Training-set accuracy score: 0.9852


### Hyperparameter Tuning

In [47]:
svc_1 = SVC(C = 100.0)
svc_1.fit(X_train,y_train)

y_pred = svc_1.predict(X_test)

print('Model accuracy score with rbf kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with rbf kernel and C=100.0 : 0.9053


In [49]:
y_pred_train = svc_1.predict(X_train)

In [50]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 1.0000


In [43]:
scv_2 = SVC(C = 1000.0)
scv_2.fit(X_train,y_train)

y_pred = scv_2.predict(X_test)

print('Model accuracy score with rbf kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with rbf kernel and C=1000.0 : 0.9053


### Kernel Trick

In [44]:
linear_svc=SVC(kernel='linear', C=1.0) 
linear_svc.fit(X_train,y_train)
y_pred_linear = linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_linear)))

Model accuracy score with linear kernel and C=1.0 : 0.7692


In [45]:
linear_svc=SVC(kernel='linear', C=1000.0) 
linear_svc.fit(X_train,y_train)
y_pred_linear = linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_linear)))

Model accuracy score with linear kernel and C=1.0 : 0.7219


In [57]:
poly_svc = SVC(kernel = 'poly')
poly_svc.fit(X_train,y_train)

y_pred_poly = poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_poly)))



Model accuracy score with polynomial kernel and C=1.0 : 0.7811


In [63]:
poly_svc = SVC(kernel = 'poly', C=1000)
poly_svc.fit(X_train,y_train)

y_pred_poly = poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_poly)))



Model accuracy score with polynomial kernel and C=1000.0 : 0.8402


In [61]:
sigmoid_svc = SVC(kernel = 'sigmoid', C = 1.0)
sigmoid_svc.fit(X_train,y_train)

y_pred_sigmoid = sigmoid_svc.predict(X_test)

print('Model accuracy score with sigmoid kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_sigmoid)))

Model accuracy score with sigmoid kernel and C=1.0 : 0.7041


In [62]:
sigmoid_svc = SVC(kernel = 'sigmoid', C = 100.0)
sigmoid_svc.fit(X_train,y_train)

y_pred_sigmoid = sigmoid_svc.predict(X_test)

print('Model accuracy score with sigmoid kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_sigmoid)))

Model accuracy score with sigmoid kernel and C=1.0 : 0.6036


### Inference

Highest Test set accuracy is obtained using RBF Kernal Trick. 
The value of C and Gamma stills needs optimization. At C = 100, Test set accuracy is high but Training Set accuracy is 1, which means Overfitting. 

Continuing with Default Parameters, calculating confusion matrix, F1 scores.

In [64]:
from sklearn.metrics import confusion_matrix

In [66]:
cm = confusion_matrix(y_test,y_pred_default)

In [68]:
print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])


Confusion matrix

 [[74 15]
 [ 7 73]]

True Positives(TP) =  74

True Negatives(TN) =  73

False Positives(FP) =  15

False Negatives(FN) =  7


In [69]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_default))

              precision    recall  f1-score   support

         0.0       0.91      0.83      0.87        89
         1.0       0.83      0.91      0.87        80

   micro avg       0.87      0.87      0.87       169
   macro avg       0.87      0.87      0.87       169
weighted avg       0.87      0.87      0.87       169



In [70]:
TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

### Kfold 

In [73]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [87]:
kfold = KFold(n_splits=5, shuffle=True)
kfold_svc = SVC()
default_kfold_scores = cross_val_score(kfold_svc,X,y, cv = kfold)

In [88]:
print('Stratified cross-validation scores with RBF kernel:\n\n{}'.format(default_kfold_scores))

Stratified cross-validation scores with RBF kernel:

[0.71005917 0.79289941 0.72189349 0.69822485 0.75739645]


In [90]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

svc = SVC()

param_grid = {'C': [0.1, 1, 10, 100, 1000],  
              'gamma':[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9], 
              'kernel': ['rbf']}  

grid_search = GridSearchCV(estimator=svc, param_grid=param_grid, scoring='accuracy', cv = kfold, verbose = 0)

In [91]:
grid_search.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=True),
       error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [92]:
grid_search.best_score_

0.936094674556213

In [93]:
grid_search.best_params_

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}

In [94]:
grid_search.best_estimator_

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### Hyperparameter C = 10 and gamma = 0.1, kernel = 'rbf

In [95]:
kfold = KFold(n_splits=5, shuffle=True)
kfold_svc = SVC(C = 10,gamma=0.1 )
kfold_scores = cross_val_score(kfold_svc,X,y, cv = kfold)


In [101]:
kfold_scores

array([0.9112426 , 0.95857988, 0.91715976, 0.97633136, 0.91715976])

In [102]:
kfold_scores.mean()

0.936094674556213